#define HAVE_DLFCN_H 1 
#define HAVE_ERFC 1 
#define HAVE_FLOAT_H 1 
#define HAVE_FLOOR 1 
#define HAVE_INTTYPES_H 1 
#define HAVE_LIBGSLCBLAS 1 
#define HAVE_LIBLAPACK 1 
#define HAVE_LIBM 1 
#define HAVE_LIMITS_H 1 
#define HAVE_MALLOC 1 
#define HAVE_MEMORY_H 1 
#define HAVE_MODF 1 
#define HAVE_POW 1 
#define HAVE_REALLOC 1 
#define HAVE_SQRT 1 
#define HAVE_STDINT_H 1 
#define HAVE_STDLIB_H 1 
#define HAVE_STRCHR 1 
#define HAVE_STRINGS_H 1 
#define HAVE_STRING_H 1 
#define HAVE_SYS_STAT_H 1 
#define HAVE_SYS_TYPES_H 1 
#define HAVE_UNISTD_H 1 
